source 'https://rubygems.org'

gem 'rails', '3.2.22.5'
gem 'pg', '0.18.0'
gem 'devise', '~> 3.5'
gem 'jwt', '~> 1.5'
gem 'active_model_serializers', '~> 0.9.5'
gem 'rspec-rails', '~> 2.14'
gem 'factory_girl_rails', '~> 4.5'
gem 'database_cleaner', '~> 1.5'
gem 'letter_opener', '~> 1.3'
gem 'bcrypt-ruby', '~> 3.1.2', require: 'bcrypt'
gem 'rack-cors', '~> 0.2.9'
gem 'redis', '~> 3.2.2'
gem 'sidekiq', '~> 2.14'
gem 'will_paginate', '~> 3.0'
