development:
  adapter: postgresql
  encoding: unicode
  database: puntos_point_app_development
  pool: 5
  username: postgres
  password: sebastian10
  min_messages: notice  # Shows basic messages like warnings and errors.
  host: db
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: puntos_point_app_test
  pool: 5
  username: postgres
  password: sebastian10
  min_messages: notice  # Shows basic messages like warnings and errors.
  host: db
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: puntos_point_app_production
  pool: 5
  username: postgres
  password: sebastian10
  min_messages: notice  # Shows basic messages like warnings and errors.
  host: db
  port: 5432
